# Generated by Django 2.2.24 on 2022-03-15 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0018_auto_20210409_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='compensation',
            field=models.ForeignKey(blank=True, help_text='Het bedrag dat wordt gegeven moet in verhouding zijn tot wat er aan de deelnemer wordt gevraagd. Het bedrag mag niet zo hoog zijn dat deelnemers in de verleiding komen om iets te doen wat ze nooit zouden doen wanneer er geen geld tegenover staat.', null=True, on_delete=django.db.models.deletion.CASCADE, to='studies.Compensation', verbose_name='Welke vergoeding krijgt de deelnemer voor zijn/haar deelname?'),
        ),
        migrations.AlterField(
            model_name='study',
            name='passive_consent',
            field=models.BooleanField(blank=True, help_text='Wanneer u kinderen via een instelling (dus ook school) werft en u de ouders niet laat ondertekenen, maar in plaats daarvan de leiding van die instelling, dan maakt u gebruik van passieve informed consent. U kunt de templates vinden op de website van de  <a href="https://Deelkracht.nl" target="_blank">ETC-SACB</a>.', null=True, verbose_name='Maakt u gebruik van passieve informed consent?'),
        ),
        migrations.AlterField(
            model_name='study',
            name='traits',
            field=models.ManyToManyField(blank=True, to='studies.Trait', verbose_name='Selecteer de bijzondere kenmerken van uw deelnemers'),
        ),
    ]
